version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env


volumes:
  mongo-data:
  mongo-configdb:
